### PR TITLE
Added gallery option for cycling through each image

### PR DESCRIPTION
**Pull request by hyperking**
@jsor there were a few issues that weren't resolved due to the limited scope of this plugin.

I made some small adjustments and added previous and next image buttons.
I'm not the best at compiling but I've added the js directly into the src file and some styling into the .less file.

Like to know your thoughts. Cheers

### CODE REVIEW

**Comment by jsor** [comment]
Thanks for your efforts. But as said in #11, i unfortunately have to reject this PR as this feature is out of the scope of Lity.

**Comment by C99nl** [comment]
It's a shame you haven't made this yet.
I can tell you, if Lity just had that functionality, of having a gallery, it'll rock so much and so many people would use it.
I guess you don't really care about your users' opinions and about what people want.

Yes I know you want to keep it a simple tiny plugin, but a gallery is something which should be added by default in a plugin like this.

**Comment by jsor** [comment]
I find the argument i "don't really care about users' opinions" because i don't want to implement a feature you need relatively disrespectful.

I wrote Lity because i needed a simple Lightbox plugin **without** any bloat like gallery features etc. and i open-sourced it because i thought it might be useful for others.

Additionally, this feature isn't as simple as this PR suggests and Lity provides a lot of extension points which can be used to implement this feature as an external extension. If there is an event or hook missing, i'm happy to accept PR's for this.

**Comment by C99nl** [comment]
@jsor The argument might be disrespectful to you, but it's the truth. Look at how many people are requesting this feature and you just don't want to build it in.
You don't have to create anything, it has been made already, all you have to do is approve it so everyone can take advantage of it. ;)
But well, good luck.

**Comment by jsor** [comment]
Wow, in the future, you should really try not to act like an ass when trying to convience people to do your work. I recommend to create your first repository, start maintaining an open-source project and then come back and we talk again. Good bye.

**Comment by C99nl** [comment]
@jsor 
Not acting an ass, not trying to convince you to do my work.
Having a repository and maintaining an open-source project has absolutely nothing to do with this case.

I actually already maintain an open-source project on BitBucket.

**Comment by egermani** [comment]
I respect Jan's desire to keep Lity light, but didn't feel like going to another plugin in order to achieve a gallery. So I ended up using an iframe that contained a slick carousel. That worked pretty well, except it was glitchy on mobile. Turns out that Safari's iframe handling conflicts with iframes, and you can get around it by setting the width of the carousel container to 1px and the min-width to 100%. I learned about that fix from here: http://www.spacevatican.org/2015/4/7/on-mobile-safari-and-iframes/

Just thought I'd drop this here in case someone else googles there way here.

Thanks for you work on Lity, Jan!

**Pull request closed without merging**
